url: "https://www.risetkd.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Rise Taekwon-Do" # the name of your site, e.g. ACME Corp.
desc: Martial arts school teaching ITF Taekwon-Do in north London since 2024.
lang: en-GB
plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from